version: "3"

services:
  mysqldb:
    image: mysql:8.0.33
    container_name: mysqldb
    ports:
      - 3307:3307
    # 환경 변수 설정
    environment:
      MYSQL_ROOT_PASSWORD: 980915
      TZ: Asia/Seoul
    # 명렬어 설정
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  springbootapp:
    image: sniij/docker-eco:0.0.1
    build:
      context: .
    container_name: springbootapp
    ports:
      - 8888:8888
    restart: unless-stopped
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate