server:
  port: 8888
spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/eco
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    schemas: eco
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
    open-in-view: false

serviceKey: ${serviceKey}

---

spring:
  config:
    import: "aws-parameterstore:"
    activate:
      on-profile: dev
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    schemas: eco
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
    open-in-view: false

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static: